class AuthLocators:

    email_create         = "//input[@id='email_create']"
    submit_create        = "//button[@id='SubmitCreate']"
    checkbox_gender_male = "//input[@id='id_gender1']"
    cust_fname           = "//input[@id='customer_firstname']"
    cust_lname           = "//input[@id='customer_lastname']"
    password             = "//input[@id='passwd']"
    days                 = "//select[@id='days']"
    months               = "//select[@id='months']"
    years                = "//select[@id='years']"
    state                = "//div[@id='uniform-id_state']//select[@id='id_state']"
    newsletter           = "//input[@id='newsletter']"
    offers               = "//input[@id='optin']"
    city                 = "//input[@id='city']"
    company              = "//input[@id='company']"
    address              = "//input[@id='address1']"
    postal               = "//input[@id='postcode']"
    mobile               = "//input[@id='phone_mobile']"
    register             = "//button[@id='submitAccount']"
    dropdown_state_label = "//div[@id='uniform-id_state']"
    customer_tab         = "//a[@title='View my customer account']"
