class AuthLocators:
    EMAIL_CREATE = "//input[@id='email_create']"
    SUBMIT_CREATE = "//button[@id='SubmitCreate']"
    CHECKBOX_GENDER_NAME = "//input[@id='id_gender1']"
    CUST_FNAME = "//input[@id='customer_firstname']"
    CUST_LNAME = "//input[@id='customer_lastname']"
    PASSWORD = "//input[@id='passwd']"
    DAYS = "//select[@id='days']"
    MONTHS = "//select[@id='monthss']"
    YEARS = "//select[@id='years']"
    STATE = "//div[@id='uniform-id_state']//select[@id='id_state']"
    NEWSLETTER = "//input[@id='newsletter']"
    OFFERS = "//input[@id='optin']"
    CITY = "//input[@id='city']"
    COMPANY = "//input[@id='company']"
    ADDRESS = "//input[@id='address1']"
    POSTAL = "//input[@id='postcode']"
    MOBILE = "//input[@id='phone_mobile']"
    REGISTER = "//button[@id='submitAccount']"
    DROPDOWN_STATE_LABEL = "//div[@id='uniform-id_state']"
    CUSTOMER_TAB = "//a[@title='View my customer account']"
